### ISSUE TITLE
Please encrypt API-Key

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/plugin-sentry#32]
The API key for sentry is specific for an adapter, by having it plain-text in  system.adapter.>adapternamespace< incorrect information or even manipulated data could be transmitted.

The API key should be encrypted to avoid abuse and usage in non-validate sources, in current situation the key is visible plain text in admin object and every adapter-github repository

**Comment by Apollon77** [comment]
It is in fact not the API key, but the project DSN which is supposed to be publicly exposed. Yes there is the risk of someone sending manipulated data but the dsn can easiely be revoked.

And even then it makes no sense to encrypt it because the code to decrypt is would be also on the same machine in visible javascript code, so there is no point :-(
